### ISSUE TITLE
Refreshing the system is adding a new broadcast every time

### ISSUE THREAD

**Issue by aaronpowered** [danielsz/sente-system#5]
Somehow the previous broadcast can't stop for me.

Anyway this is awesome!

**Comment by danielsz** [comment]
I think you've encountered [ghosts in the machine](https://danielsz.github.io/blog/deft-49.html). 

This repo is mainly for reference purposes with regards to `sente` and I'm not overly concerned about reloading issues (because priorities). The [system-websockets](https://github.com/danielsz/system-websockets) is closer to the way I wire sente in my apps. I don't think it occurs there, but if it does, you're welcome to open a ticket there. Thank you.

**Comment by aaronpowered** [comment]
Thanks for the quick reply!
